services:
  web:
    build: .
    ports:
      - "3636:3636"
    volumes:
      - textjar-data:/app/db
      - textjar-photos:/app/photos
      - ./templates:/app/templates
      - ./static:/app/static
      - /app/static/dist
    environment:
      - GIN_MODE=release
volumes:
  textjar-data:
  textjar-photos:
