services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - textjar-data:/app/db
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - GIN_MODE=release
volumes:
  textjar-data:
